### ISSUE TITLE
Customize generated class

### ISSUE THREAD

**Issue by jobayle** [gradle/cucumber-companion#116]
Hi and thank you for this plugin.

To support our use case, we need the generated class to have an extra annotation.
Could you please add a way to customize the output?

I can see in `CompanionGenerator.java` that using a templating engine is deemed overkill.

For us, something as simple as specifying a base class would do it, but for others new issues may arise, eg: what if specific features require to inherit from specific parent class...

Thanks!

**Comment by skuzzle** [comment]
This sounds like a reasonable use case to me, but we should think about what aspects of the generated file really needs to be customizable. So the obvious possibilities are:

* add option to add base class to generated files
* add option to add interface(s) to generated files
* add option to add class level annotations to generated files

I'm not sure if all 3 options would be equally useful, but OTOH it would not add much overhead doing all 3. @gradle/dv-testing-team WDYT?

I can not promise any timeline for adding this feature but we are of course open to contributions 😉

**Comment by pshevche** [comment]
This sounds like a reasonable feature. @jobayle, would you be interested in giving it a shot yourself? We'd like to implement the 3 scenarios @skuzzle described above. Implementing all of them seems like the same effort as addressing just your scenario. We propose the following API:

```
cucumberCompanion {
    customizeGeneratedClasses {
        classAnnotations = <list of FQN of annotation classes>
        baseClass = <FQN of base class>
        interfaces = <list of FQN of interface classes>
    }
}
```

You can use [this PR](https://github.com/gradle/cucumber-companion/pull/82) as a reference for propagating data from the task extension to the `CompanionGenerator`.

Please let us know if you don't have time to work on it. We'll then see what we can do.

**Comment by leonard84** [comment]
I'll take a look at implementing it.
