### ISSUE TITLE
only first resources source directory configured in JVM Test Suite Plugin is processed

### ISSUE THREAD

**Issue by lnhrdt** [gradle/cucumber-companion#133]
When using the Cucumber Companion plugin with the JVM Test Suite Plugin, only feature files from the first resource directory (configured in the resources block) are used for generating tests. Feature files in subsequent directories seem to be ignored.

## minimal reproducible example:

https://github.com/lnhrdt/cucumber-companion-multiple-sources-issue

## steps

1. run: `./gradlew :suite:featuresGenerateCucumberSuiteCompanion`
2. inspect: `suite/build/generated-sources/cucumberCompanion-features`
3. change order of sources in `suite/build.gradle.kts`

```
        resources.setSrcDirs(
          listOf<File>(
            checkNotNull(project(":features-a").sourceSets["main"].output.resourcesDir),
            checkNotNull(project(":features-b").sourceSets["main"].output.resourcesDir),
          )
        )
```

4. rerun/reinspect

## side note

I also noticed that the generated sources do not seem to be cleaned up when the source changes. If a class is generated for a feature, then the feature is removed, then classes are generated, the old class is still there. (let me know if you'd prefer a separate issue for this).

**Comment by leonard84** [comment]
Hi @lnhrdt, we are currently busy with other work and won't get to this in the near future, but if you want to work on this, here are some pointers.

We have a [task](https://github.com/gradle/cucumber-companion/blob/main/gradle-plugin/src/main/kotlin/com/gradle/cucumber/companion/GenerateCucumberSuiteCompanionTask.kt#L32-L33) configured via a [helper](https://github.com/gradle/cucumber-companion/blob/main/gradle-plugin/src/main/kotlin/com/gradle/cucumber/companion/CucumberCompanionHelper.kt#L68-L69) that either takes the standard [test source set](https://github.com/gradle/cucumber-companion/blob/main/gradle-plugin/src/main/kotlin/com/gradle/cucumber/companion/CucumberCompanionPlugin.kt#L44) or the source set of a test suite. Currently, the task only has a single `DirectoryProperty`, but the source set can have multiple resource dirs.
To fix this, the `DirectoryProperty` should be changed to a `ConfigurableFileCollection`. 

You can wire  [SourceDirectorySet#getSourceDirectories()](https://github.com/gradle/gradle/blob/689200d0b32ab4873d0a71f72ed4b0a94df75120/subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java#L107) directly to it, so it's "live".

You need to add a runtime check when using the data from the `ConfigurableFileCollection` to check that it only contains directories, as the generator doesn't support single files at the moment.

**Comment by lnhrdt** [comment]
Hey @leonard84, I see you got to it before I did! Just wanted to say, thanks for the followup, the pointers to potentially work on the PR myself, and for the fix.

I'll check out the new version soon.

**Comment by lnhrdt** [comment]
@leonard84 I wanted to share that I checked out the new version in my projects and 1.3.0 fixes the issue in all my use cases. Thank you again!
